## Working with numerical data

The "data" in *Data Analysis* typically refers to numerical data, e.g., stock prices, sales figures, sensor measurements, sports scores, database tables, etc. The [Numpy](https://numpy.org) library provides specialized data structures, functions, and other tools for numerical computing in Python. Let's work through an example to see why & how to use Numpy for working with numerical data.


> Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in  millimeters) & average relative humidity (in percentage) as a linear equation.
>
> `yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`

We're expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might come up with reasonable values for the weights `w1`, `w2`, and `w3`. Here's an example set of values:

In [1]:
w1, w2, w3  = 0.3, 0.2, 0.5

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yield_apples = kanto_temp*w1 + kanto_rainfall*w2 + kanto_humidity*w3

In [4]:
kanto_yield_apples

56.8

In [5]:
print('The expected yield of apples in kanto region is {} is tonnes per hectare.'.format(kanto_yield_apples))

The expected yield of apples in kanto region is 56.8 is tonnes per hectare.


To make it easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector,i.e a list of numbers

In [6]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

The three numbers in each vector represent the temperature, rainfall, and humidity data, respectively. 

We can also represent the set of weights used in the formula as a vector.

In [7]:
weights= [w1,w2,w3]

In [8]:
def crop_yield(region, weights):
    result = 0
    for x,w in zip(region, weights):
        result += x*w
    return result

In [9]:
crop_yield(kanto, weights)

56.8

In [10]:
crop_yield(johto, weights)

76.9

In [11]:
crop_yield(unova, weights)

74.9

## Going from Python lists to Numpy arrays


The calculation performed by the `crop_yield` (element-wise multiplication of two vectors and taking a sum of the results) is also called the *dot product*. 
The Numpy library provides a built-in function to compute the dot product of two vectors. However, we must first convert the lists into Numpy arrays.

Let's install the Numpy library using the `pip` package manager.

In [12]:
import numpy as np

We can now use the `np.array` function to create Numpy arrays.

In [13]:
kanto = np.array([73,67,43])

In [14]:
kanto

array([73, 67, 43])

In [15]:
weights = np.array([w1,w2,w3])

In [16]:
weights

array([0.3, 0.2, 0.5])

In [17]:
type(kanto)

numpy.ndarray

In [18]:
type(weights)

numpy.ndarray

Just like lists,Numpy also supports the indexing notation [].

In [19]:
weights[0]

np.float64(0.3)

In [20]:
kanto[2]

np.int64(43)

## Operating on Numpy arrays

We can now compute the dot product of the two vectors using the `np.dot` function.

In [21]:
np.dot(kanto, weights)

np.float64(56.8)

We can achieve the same result with low-level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the resulting numbers' sum.

In [22]:
(kanto*weights).sum()

np.float64(56.8)

The `*` operator performs an element-wise multiplication of two arrays if they have the same size. The `sum` method calculates the sum of numbers in an array.

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [24]:
arr1*arr2

array([ 4, 10, 18])

In [25]:
arr2.sum()

np.int64(15)

## Benefits of using Numpy arrays

Numpy arrays offer the following benefits over Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise, and intuitive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yield`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime

Here's a comparison of dot products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [26]:
#Py lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

#Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [27]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 141 ms
Wall time: 163 ms


833332333333500000

In [28]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 1.08 ms


np.int64(833332333333500000)

As you can see, using `np.dot` is 100 times faster than using a `for` loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

Let's save our work before continuing.

## Multi-dimensional Numpy arrays 

We can now go one step further and represent the climate data for all the regions using a single 2-dimensional Numpy array.

In [29]:
climate_data = np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]])

In [30]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

If you've taken a linear algebra class in high school, you may recognize the above 2-d array as a matrix with five rows and three columns. Each row represents one region, and the columns represent temperature, rainfall, and humidity, respectively.

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">


In [31]:
#2d array
climate_data.shape

(5, 3)

In [32]:
weights


array([0.3, 0.2, 0.5])

In [34]:
#1d array
weights.shape

(3,)

In [35]:
#3d array
arr3 = np.array([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.5]]])

In [36]:
arr3.shape

(2, 2, 3)

All the elements in a numpy array have the same data type. You can check the data type of an array using the `.dtype` property.

In [37]:
weights.dtype

dtype('float64')

In [39]:
climate_data.dtype

dtype('int64')

In [40]:
weights.dtype

dtype('float64')

If an array contains even a single floating point number, all the other elements are also converted to floats.

In [41]:
arr3.dtype

dtype('float64')

We can now compute the predicted yields of apples in all the regions, using a single matrix multiplication between `climate_data` (a 5x3 matrix) and `weights` (a vector of length 3). Here's what it looks like visually:

<img src="https://i.imgur.com/LJ2WKSI.png" width="240">


We can use the `np.matmul` function or the `@` operator to perform matrix multiplication.

<!-- kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70] -->

In [43]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [44]:
weights

array([0.3, 0.2, 0.5])

In [45]:
# kanto = [73,67,43]
# johto = [91,88,64]
# hoenn = [87,134,58]
# sinnoh = [102,43,37]
# unova = [69,96,70]


# w1, w2, w3  = 0.3, 0.2, 0.5

np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [47]:
climate_data @ weights  #Alternative way we can also use @ instead of np.matmul

array([56.8, 76.9, 81.9, 57.7, 74.9])

## Working with CSV data files

Numpy also provides helper functions reading from & writing to files. Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:


```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

This format of storing data is known as *comma-separated values* or CSV. 

> **CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)


To read this file into a numpy array, we can use the `genfromtxt` function.

In [48]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2f6bd207740>)

In [49]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [50]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [52]:
climate_data.shape #rows,col

(10000, 3)

We can now perform a matrix multiplication using the `@` operator to predict the yield of apples for the entire dataset using a given set of weights.

In [53]:
weights = np.array([0.3,0.2,0.5])

In [54]:
yields = climate_data @ weights

In [55]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [56]:
yields.shape

(10000,)

Let's add the `yields` to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

In [57]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)),axis = 1)

In [58]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

There are a couple of subtleties here:

* Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.

*  The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function to change the shape of `yields` from `(10000,)` to `(10000,1)`.

Here's a visual explanation of `np.concatenate` along `axis=1` (can you guess what `axis=0` results in?):

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

The best way to understand what a Numpy function does is to experiment with it and read the documentation to learn about its arguments & return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.

Let's write the final results from our computation above back to a file using the `np.savetxt` function.

In [59]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [63]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

The results are written back in the CSV format to the file `climate_results.txt`. 

```
temperature,rainfall,humidity,yeild_apples
25.00,76.00,99.00,72.20
39.00,65.00,70.00,59.70
59.00,45.00,77.00,65.20
84.00,63.00,38.00,56.80
...
```


Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

In [69]:
arr1 = np.array([3353,343,343])
arr2 = np.array([343,3434,43])

In [75]:
total = np.sum(np.concatenate((arr1,arr2)))

In [77]:
total

np.int64(7859)

In [79]:
total_matrix = arr1+arr2

In [81]:
total_matrix

array([3696, 3777,  386])

## Arithmetic operations, broadcasting and comparison

Numpy arrays support arithmetic operators like `+`, `-`, `*`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [82]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])

In [84]:
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,14]])

In [85]:
# Adding a scalar to an array
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [87]:
#Element awise sub
arr3 -arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 11]])